### ISSUE TITLE
Cloning during a release fails if the feature branch has been deleted

### ISSUE THREAD

**Issue by markvincze** [estafette/estafette-ci#15]
If we have cloning on a release enabled with

```
clone: true
```

And we try to release a build which was done on a feature branch, which since then has been merged and the branch was deleted, the cloning fails with this error:

```
Cloning git repository foo to branch bar and revision c8cbaf0c359e0fd605bd86a345fad34f0f6e5cd1 with shallow clone is true and depth 50...
Cloning into '/estafette-work'...
warning: Could not find remote branch bar to clone.
fatal: Remote branch bar not found in upstream origin
```

Is this a bug or as designed?  
I'm not sure if this can be solved though, so when we merge a PR and check "Delete branch", whether that only removes the branch marker, or if it actually deletes all the commits in the branch. If it removes the actual commits, then we might not be able to solve it. In that case maybe we should ask the devs not to use the "Delete branch" option when they merge their PRs?

**Comment by JorritSalverda** [comment]
I would expect the release to be done from the merge commit, which is likely on a branch that's still there. Why would you still want to release the non-existing branch? To make this work we would have to figure out which branch the commit has been merged into and clone that instead. Practically very hard, so curious about the use case.
